# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpLanguageSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=500)),
                ('consent_line1', models.CharField(max_length=500)),
                ('consent_line2', models.CharField(max_length=500)),
                ('consent_line3a', models.CharField(max_length=500)),
                ('consent_line3b', models.CharField(max_length=500)),
                ('consent_line3c', models.CharField(max_length=500)),
                ('consent_line3d', models.CharField(max_length=500)),
                ('consent_line3e', models.CharField(max_length=500)),
                ('consent_line4a', models.CharField(max_length=500)),
                ('consent_line4b', models.CharField(max_length=500)),
                ('consent_line5', models.CharField(max_length=500)),
                ('consent_line6', models.CharField(max_length=500)),
                ('consent_line7', models.CharField(max_length=500)),
                ('datareq_line1', models.CharField(max_length=500)),
                ('datareq_line2', models.CharField(max_length=500)),
                ('datareq_line3', models.CharField(max_length=500)),
                ('datareq_line4', models.CharField(max_length=500)),
                ('datareq_line5', models.CharField(max_length=500)),
                ('datareq_line6', models.CharField(max_length=500)),
                ('partners_line1', models.CharField(max_length=500)),
                ('partners_line2', models.CharField(max_length=500)),
                ('partners_line3', models.CharField(max_length=500)),
            ],
        ),
    ]
