# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0002_popuplanguagesupport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popuplanguagesupport',
            old_name='consent_line3b',
            new_name='duration_wrapper1',
        ),
        migrations.AddField(
            model_name='popuplanguagesupport',
            name='duration_undetermined',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
