# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0006_removalqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalqueue',
            name='removal_request_date',
            field=models.DateTimeField(),
        ),
    ]
