# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0007_auto_20180418_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalqueue',
            name='last_order_date',
            field=models.DateTimeField(),
        ),
    ]
