# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0008_auto_20180418_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exports', models.IntegerField(default=0)),
                ('last_exportdatetime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
