# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0009_exportlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportLogs',
        ),
    ]
