# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0010_delete_exportlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='popuplanguagesupport',
            name='tabtitle1',
            field=models.CharField(default='Policy', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popuplanguagesupport',
            name='tabtitle2',
            field=models.CharField(default='Sharing', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popuplanguagesupport',
            name='tabtitle3',
            field=models.CharField(default='Access', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popuplanguagesupport',
            name='tabtitle4',
            field=models.CharField(default='Removal', max_length=500),
            preserve_default=False,
        ),
    ]
