# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=500)),
                ('auth_token', models.CharField(max_length=500)),
                ('install_date', models.DateTimeField(default='2001-01-01 00:00:00')),
                ('uninstall_date', models.DateTimeField(default='2001-01-01 00:00:00')),
            ],
        ),
    ]
