# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0004_auto_20180207_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='installtracker',
            name='initial_import',
            field=models.BooleanField(default=False),
        ),
    ]
