# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0006_auto_20180320_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeatz',
            name='last_import_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
