# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0007_shopdeatz_last_import_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeatz',
            name='download_key',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
