# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0008_shopdeatz_download_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeatz',
            name='charge_id',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
