# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0010_installtracker_db_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeatz',
            name='shop_name',
            field=models.CharField(default='JerrysJerseyStore', max_length=500),
            preserve_default=False,
        ),
    ]
