# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0011_shopdeatz_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdeatz',
            name='last_exportdatetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shopdeatz',
            name='last_partner_change_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shopdeatz',
            name='total_exports',
            field=models.IntegerField(default=0),
        ),
    ]
