# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0012_auto_20180420_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='installtracker',
            name='uninstaller_email',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
