# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcustomizations',
            name='font_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='templatedefaults',
            name='font_size',
            field=models.CharField(max_length=100),
        ),
    ]
