# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180312_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_var_name', models.CharField(max_length=100)),
                ('font_linkrel_name', models.CharField(max_length=100)),
                ('fonr_css_string', models.CharField(max_length=100)),
            ],
        ),
    ]
