# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180313_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownPartnersServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_lookup_var', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('service_link', models.CharField(default='-', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShopMarketingServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=300)),
                ('known_services_list', models.CharField(default='shopify,gdpr,', max_length=500)),
                ('unknown_services_list', models.CharField(default='-', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=300)),
                ('datapurpose_shipping', models.BooleanField(default=True)),
                ('datapurpose_payproc', models.BooleanField(default=True)),
                ('datapurpose_emarketing', models.BooleanField(default=True)),
                ('datapurpose_retar', models.BooleanField(default=True)),
                ('storage_duration', models.IntegerField(default=0)),
                ('data_sharing', models.CharField(default='-', max_length=100)),
                ('third_country', models.CharField(default='-', max_length=100)),
                ('esp', models.CharField(default='-', max_length=100)),
                ('subscriber_list_id', models.CharField(default='-', max_length=500)),
            ],
        ),
    ]
