# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_knownpartnersservicedetails_shopmarketingservices_shopsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmarketingservices',
            name='known_services_list',
        ),
        migrations.AddField(
            model_name='shopmarketingservices',
            name='known_services_list_quoted',
            field=models.CharField(default='shopify,gdpr', max_length=500),
        ),
        migrations.AddField(
            model_name='shopmarketingservices',
            name='known_services_list_unquoted',
            field=models.CharField(default='"shopify","gdpr"', max_length=500),
        ),
    ]
