# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180315_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=300)),
                ('esp_username', models.CharField(default='-', max_length=500)),
                ('esp_API_key', models.CharField(default='-', max_length=500)),
                ('esp_api_endpoint_url', models.CharField(default='-', max_length=500)),
                ('esp_data_center', models.CharField(default='-', max_length=500)),
                ('mailchimp', models.BooleanField(default=False)),
                ('aweber', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='shopmarketingservices',
            name='known_services_list_quoted',
            field=models.CharField(default='"shopify","gdpr"', max_length=500),
        ),
    ]
