# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180316_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espcredentials',
            name='aweber',
        ),
        migrations.RemoveField(
            model_name='espcredentials',
            name='mailchimp',
        ),
        migrations.AddField(
            model_name='espcredentials',
            name='configured_ESP',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
