# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180316_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmarketingservices',
            name='known_services_list_unquoted',
            field=models.CharField(default='shopify,gdpr', max_length=500),
        ),
    ]
