# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_advancedsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsettings',
            name='ip_filtering_active',
            field=models.BooleanField(default=True),
        ),
    ]
