# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_advancedsettings_ip_filtering_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomizations',
            name='secondary_text_color',
            field=models.CharField(default='#bbb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatedefaults',
            name='secondary_text_color',
            field=models.CharField(default='#bbb', max_length=100),
            preserve_default=False,
        ),
    ]
