# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180430_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomizations',
            name='active_tab_text_color',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatedefaults',
            name='active_tab_text_color',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
