# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180430_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcustomizations',
            name='widget_behaviour',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='templatedefaults',
            name='widget_behaviour',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
